// This file is auto-generated by Lovable. Do not modify it.
// NOTE: Updated to use Appwrite instead of Supabase for the ShopMate Pro migration.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { account } from "../appwrite/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      // Appwrite handles OAuth sessions via its own flow;
      // this integration point is kept for compatibility with Lovable's auth scaffold.
      try {
        // The Appwrite session is already managed by the OAuth2 redirect flow.
        // If Lovable provides tokens, we can attempt to create a session,
        // but typically the Appwrite OAuth2 flow handles this automatically.
        console.log("[lovable] OAuth completed, Appwrite session managed by redirect flow.");
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
